@echo off


call LOG_ENTER pENV

CALL sENV

SET "PROJ_LABEL=%SYS%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%GEO_CONT%"
SET "PROJ_CONT_DATA_DIR=%GEO_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%GEO_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%GEO_CONT_HOME_DIR%"
SET "PROJ_HOST=%GEO_HOST%"
SET "PROJ_HOST_DIR=%GEO_HOST_DIR%"
SET "PROJ_IMG=%GEO_IMG%"
SET "PROJ_PASSWORD=%GEO_PASSWORD%"
SET "PROJ_PORT_EXT=%GEO_PORT_EXT%"
SET "PROJ_PORT_INT=%GEO_PORT_INT%"
SET "PROJ_USER=%GEO_USER%"
SET "PROJ_VOL=%GEO_VOL%"
SET "PROJ_VOL_DIR=%GEO_VOL_DIR%"

SET "PROJ_DB_NAME=%GEO_DB_NAME%"

call LOG_EXIT pENV
